COST_COUNTER_RESET_VALUE = 0
QUERY_COST = 0.1

ALPHA_VANTAGE = 'AlphaVantage'
REDIS = 'redis'

STOCK_QUOTE_DATA = "stock_quote_data"
COST_COUNTER = "cost_counter"

SYMBOL = "symbol"
UPDATE_TIME = "update_time"
PRICE = "price"
CHANGE_PERCENT = "change_percent"
HIGH_LOW_RATIO = "high_low_ratio"

TRADING_HOUR_START = 10
TRADING_HOUR_END = 17
CACHE_DURATION_HIGH_VOLATILITY = 10 * 60  # 10 minutes
CACHE_DURATION_LOW_VOLATILITY = 20 * 60  # 20 minutes
CACHE_DURATION_NON_TRADING = 60 * 60  # 1 hour
HIGH_LOW_RATIO_THRESHOLD = 1.03


